### ISSUE TITLE
Documenetation in english please

### ISSUE THREAD

**Issue by yazeed44** [ScienJus/PixivParser#1]

**Comment by ScienJus** [comment]
thanks for you message!
i will try to write some description for this project with English, and there are some problems haven't been solved i will also do.
so if you have any question, you can comment here.

ps: I saw you were downloading kancolle pictures, i'm also playing this game.
my English is terrible :(

**Comment by yazeed44** [comment]
> and there are some problems haven't been solved i will also do.

I have modifiy your api for my personal use , maybe i will add them as issues here

I have been using your api to create [a bot](https://github.com/yazeed44/PixivFetcherTelegramBot) for my anime group in telegram (You should join us if you are interested )

> I saw you were downloading kancolle pictures, i'm also playing this game.

Sadly i haven't tried the game yet , we have someone in our group who does though

Thank you for replying

**Comment by ScienJus** [comment]
i have saw your project , it's a good idea!, i will try to let it support download random picture or a few picture with limit!

**Comment by yazeed44** [comment]
Yes also there's two other bots in the group , but none of them implemened sending batches of images so i implemented one

> i have saw your project , it's a good idea!, i will try to let it support download random picture or a few picture with limit!

Thanks !

**Comment by ScienJus** [comment]
i am rewriting this project to use pixiv ios api, it will be more quickly and consumed lesser traffic, you can tell me any what you want.

**Comment by yazeed44** [comment]
> you can tell me any what you want.

Thanks .. i created new issues for now , if i got any other ideas i will create new issue

ps:As i said before , you're highly welcomed to join our group on telegram :)

**Comment by ScienJus** [comment]
i just commit the basic version of pixiv api client, and write a document for it in english and chinese, you can try it and if you have any question pleace tell me, I hope you will like it.
