### ISSUE TITLE
Callback after downloading an image or images

### ISSUE THREAD

**Issue by yazeed44** [ScienJus/PixivParser#2]

**Comment by ScienJus** [comment]
i just created the `IllustImageDownloadTask`, i think it's better than `IllustDownloadTask`

**Comment by ScienJus** [comment]
it's only download the picture to the memory, you can stored it or draw it or send to web app as you like

**Comment by yazeed44** [comment]
You mean converting `byte[]` to file ?

Because I'd rather have File object directly

**Comment by ScienJus** [comment]
yes, i don't like file because It doesn't need to be stored to disk, like draw with `java.awt.Image` or upload to another web application

**Comment by yazeed44** [comment]
Seems legit 

The new api looks great , i will try once i have some free time ^_^

Arigato

**Comment by ScienJus** [comment]
If you do not hurry to use, I will separate PixivClient and PixivApiClient to make it more readable.it makes me happy!

**Comment by yazeed44** [comment]
OK do what you like , I have other project that might some long time

> it makes me happy!

Yep there's nothing greater than developing something that people use
