### ISSUE TITLE
What does praise mean ?

### ISSUE THREAD

**Issue by yazeed44** [ScienJus/PixivParser#4]
In this method

``` java
public void searchByKeyword(String word, boolean isR18, int praise) {
```

**Comment by ScienJus** [comment]
sorry, I forgot to change this param's name.it is:
![1](https://cloud.githubusercontent.com/assets/8350653/9165149/b66729ca-3f81-11e5-8a5e-1185c9d18ab9.png)

**Comment by yazeed44** [comment]
So it's like Favorite or star  ?

**Comment by ScienJus** [comment]
yes! the method will discard picture when it's star less than the number you given

**Comment by yazeed44** [comment]
Then i guess `baseStar` is better name then ?

ps: nicomaki is otp :heart:
