### ISSUE TITLE
No images if i set to filter any image under 100 favorite

### ISSUE THREAD

**Issue by yazeed44** [ScienJus/PixivParser#8]

**Comment by ScienJus** [comment]
please tell me the key word, i'll try to search it on www.pixiv.net

**Comment by yazeed44** [comment]
```
love_live
```

The problem occurred before your commit today , i will update and see what happens

Also do i have to use your account for www.pixiv.net ?

Or can i just use my account ?

**Comment by ScienJus** [comment]
you do not have to use my account.

**Comment by yazeed44** [comment]
I know i have said this before , but do you want to join our group in telegram?

Also you can see your parser at action :smile:

**Comment by ScienJus** [comment]
i have registered Telegram, what should i do now?

**Comment by yazeed44** [comment]
Make a user name , send it to me here and I'll add you

**Comment by ScienJus** [comment]
@ScienJus
