### ISSUE TITLE
Add a method in the download call for array of the images

### ISSUE THREAD

**Issue by yazeed44** [ScienJus/PixivParser#9]
After downloading the whole illust , a method gets called for all of illust images
Also we can close the client there

**Comment by ScienJus** [comment]
i think you can close the client anytime, download thread can work after the client closed

**Comment by yazeed44** [comment]
Oh OK , what's gonna happen if i didn't close the client ?

**Comment by ScienJus** [comment]
i don't have an exact answer.maybe it's just a habit

**Comment by yazeed44** [comment]
:laughing: OK
